# Generated by Django 5.1.6 on 2025-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
